apiVersion: v1
kind: Pod
metadata:
  name: armpod
  labels:
    app: hello-app
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/compute-class: Scale-Out
    kubernetes.io/arch: arm64
  containers:
  - name: hello-app
    image: us-central1-docker.pkg.dev/gke-autopilot-test/test/hello-ma:2
